# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: first
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.apiproject_open_project_api import ApiprojectOpenProjectApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiprojectOpenProjectApi(unittest.TestCase):
    """ApiprojectOpenProjectApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.apiproject_open_project_api.ApiprojectOpenProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_open(self):
        """Test case for open

        Opens project in Pick Master.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
