# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: first
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from arcor2_kinali.swagger_client.models.pose6d import Pose6d  # noqa: F401,E501


class Move(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pose': 'Pose6d'
    }

    attribute_map = {
        'pose': 'pose'
    }

    def __init__(self, pose=None):  # noqa: E501
        """Move - a model defined in Swagger"""  # noqa: E501

        self._pose = None
        self.discriminator = None

        if pose is not None:
            self.pose = pose

    @property
    def pose(self):
        """Gets the pose of this Move.  # noqa: E501

        Pose with position and rotatation  # noqa: E501

        :return: The pose of this Move.  # noqa: E501
        :rtype: Pose6d
        """
        return self._pose

    @pose.setter
    def pose(self, pose):
        """Sets the pose of this Move.

        Pose with position and rotatation  # noqa: E501

        :param pose: The pose of this Move.  # noqa: E501
        :type: Pose6d
        """

        self._pose = pose

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Move, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Move):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
