# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pick_master_error import PickMasterError  # noqa: E501
from swagger_client.rest import ApiException


class TestPickMasterError(unittest.TestCase):
    """PickMasterError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickMasterError(self):
        """Test PickMasterError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pick_master_error.PickMasterError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
