# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: first
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vec3 import Vec3  # noqa: E501
from swagger_client.rest import ApiException


class TestVec3(unittest.TestCase):
    """Vec3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVec3(self):
        """Test Vec3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vec3.Vec3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
