# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scripting_api import ScriptingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScriptingApi(unittest.TestCase):
    """ScriptingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.scripting_api.ScriptingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scripting_run_script_from_file(self):
        """Test case for scripting_run_script_from_file

        Posts file script and execute.  # noqa: E501
        """
        pass

    def test_scripting_stop(self):
        """Test case for scripting_stop

        Stop running script.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
