# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.robot_joint import RobotJoint  # noqa: E501
from swagger_client.rest import ApiException


class TestRobotJoint(unittest.TestCase):
    """RobotJoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRobotJoint(self):
        """Test RobotJoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.robot_joint.RobotJoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
