# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.project_api import ProjectApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_put_open_project(self):
        """Test case for put_open_project

        Opens the project in Pick Master.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
