# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.robot_api import RobotApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRobotApi(unittest.TestCase):
    """RobotApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.robot_api.RobotApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_end_effector_names(self):
        """Test case for get_end_effector_names

        Gets names of end-effectors.  # noqa: E501
        """
        pass

    def test_get_io(self):
        """Test case for get_io

        Gets robot io pin value.  # noqa: E501
        """
        pass

    def test_get_joints(self):
        """Test case for get_joints

        Gets actual joints with names to rotation of robot.  # noqa: E501
        """
        pass

    def test_get_pose(self):
        """Test case for get_pose

        Gets pose of robot's end-effector.  # noqa: E501
        """
        pass

    def test_put_init_robot(self):
        """Test case for put_init_robot

        Initialize a robot system.  # noqa: E501
        """
        pass

    def test_put_joints(self):
        """Test case for put_joints

        Moves robot to specific joints rotation.  # noqa: E501
        """
        pass

    def test_put_move(self):
        """Test case for put_move

        Moves robot's end-effector to specific pose.  # noqa: E501
        """
        pass

    def test_robot_get_mesh_focus(self):
        """Test case for robot_get_mesh_focus

        Focuses mesh pivot to robot space  # noqa: E501
        """
        pass

    def test_set_io(self):
        """Test case for set_io

        Sets robot io pin value.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
