# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InitRobot(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'configuration_id': 'str',
        'restart_environment': 'bool'
    }

    attribute_map = {
        'configuration_id': 'configurationId',
        'restart_environment': 'restartEnvironment'
    }

    def __init__(self, configuration_id=None, restart_environment=None):  # noqa: E501
        """InitRobot - a model defined in Swagger"""  # noqa: E501

        self._configuration_id = None
        self._restart_environment = None
        self.discriminator = None

        if configuration_id is not None:
            self.configuration_id = configuration_id
        if restart_environment is not None:
            self.restart_environment = restart_environment

    @property
    def configuration_id(self):
        """Gets the configuration_id of this InitRobot.  # noqa: E501

        The unique identification of robot's configuration.  # noqa: E501

        :return: The configuration_id of this InitRobot.  # noqa: E501
        :rtype: str
        """
        return self._configuration_id

    @configuration_id.setter
    def configuration_id(self, configuration_id):
        """Sets the configuration_id of this InitRobot.

        The unique identification of robot's configuration.  # noqa: E501

        :param configuration_id: The configuration_id of this InitRobot.  # noqa: E501
        :type: str
        """

        self._configuration_id = configuration_id

    @property
    def restart_environment(self):
        """Gets the restart_environment of this InitRobot.  # noqa: E501

        The value indicating whether a robot environment should be restarted.  # noqa: E501

        :return: The restart_environment of this InitRobot.  # noqa: E501
        :rtype: bool
        """
        return self._restart_environment

    @restart_environment.setter
    def restart_environment(self, restart_environment):
        """Sets the restart_environment of this InitRobot.

        The value indicating whether a robot environment should be restarted.  # noqa: E501

        :param restart_environment: The restart_environment of this InitRobot.  # noqa: E501
        :type: bool
        """

        self._restart_environment = restart_environment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InitRobot, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InitRobot):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
