# coding: utf-8

"""
    Pick Master Web API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0-alpha.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.quaternion import Quaternion  # noqa: F401,E501
from swagger_client.models.vector3 import Vector3  # noqa: F401,E501


class Move(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position': 'Vector3',
        'rotation': 'Quaternion',
        'end_effector': 'str'
    }

    attribute_map = {
        'position': 'position',
        'rotation': 'rotation',
        'end_effector': 'endEffector'
    }

    def __init__(self, position=None, rotation=None, end_effector=None):  # noqa: E501
        """Move - a model defined in Swagger"""  # noqa: E501

        self._position = None
        self._rotation = None
        self._end_effector = None
        self.discriminator = None

        if position is not None:
            self.position = position
        if rotation is not None:
            self.rotation = rotation
        if end_effector is not None:
            self.end_effector = end_effector

    @property
    def position(self):
        """Gets the position of this Move.  # noqa: E501

        Gets or sets target position of the end-effector.  # noqa: E501

        :return: The position of this Move.  # noqa: E501
        :rtype: Vector3
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Move.

        Gets or sets target position of the end-effector.  # noqa: E501

        :param position: The position of this Move.  # noqa: E501
        :type: Vector3
        """

        self._position = position

    @property
    def rotation(self):
        """Gets the rotation of this Move.  # noqa: E501

        Gets or sets target rotation of the end-effector.  # noqa: E501

        :return: The rotation of this Move.  # noqa: E501
        :rtype: Quaternion
        """
        return self._rotation

    @rotation.setter
    def rotation(self, rotation):
        """Sets the rotation of this Move.

        Gets or sets target rotation of the end-effector.  # noqa: E501

        :param rotation: The rotation of this Move.  # noqa: E501
        :type: Quaternion
        """

        self._rotation = rotation

    @property
    def end_effector(self):
        """Gets the end_effector of this Move.  # noqa: E501

        Gets or sets the name of the end-effector to Move.  # noqa: E501

        :return: The end_effector of this Move.  # noqa: E501
        :rtype: str
        """
        return self._end_effector

    @end_effector.setter
    def end_effector(self, end_effector):
        """Sets the end_effector of this Move.

        Gets or sets the name of the end-effector to Move.  # noqa: E501

        :param end_effector: The end_effector of this Move.  # noqa: E501
        :type: str
        """

        self._end_effector = end_effector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Move, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Move):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
